# Generated by Django 4.2.3 on 2023-07-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date_01',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='week',
            name='date_02',
            field=models.CharField(max_length=20),
        ),
    ]
