# Generated by Django 4.2.3 on 2023-07-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_week_date_01_alter_week_date_02'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.IntegerField(),
        ),
    ]
