# Generated by Django 4.2.3 on 2023-07-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_week_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.CharField(max_length=20),
        ),
    ]
