# Generated by Django 4.2.3 on 2023-07-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_week_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="start_date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="trial_date",
            field=models.CharField(max_length=20),
        ),
    ]
