# Generated by Django 4.2.4 on 2023-09-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_course_start_date_alter_course_trial_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cyber_classes",
            field=models.CharField(default="SomeDefaultValue", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="review_class",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
