# Generated by Django 4.2.4 on 2023-09-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_course_cyber_classes_course_review_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="cyber_classes",
        ),
        migrations.AddField(
            model_name="course",
            name="classes",
            field=models.CharField(default="", max_length=20),
        ),
    ]
